appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tqiB2Id4E00Ty0c/1Rk10u98oRjHRMg3TBtKz0+v4iXlX/x+Qo7b/PygKUgkEO4twXkSf14weM0tCTi6xQgh5/vyekrTSMtlIrCks2/+vGehyf9WawfIsj8/AdpBEXVCTRI3IGaIMTMlcCiONt5+f4QQxs4ZCF6jSivjgewhMLFu7QLkFcNjwJ7ikzskVCHvk/KybJIKs5Sxo9luzu/vE5jlJX83VDDBm/ihoVhhDg8Jt7tPD/FCKYlVSfTfASf/cYj/NYFTv+aME/op1uGCJ9aucNXS/3/ucyI/IM3PQUi8uzTNikbQD2z7vhr0TMuSi0pmZ8+Vct2+igNnsBLwlUdlHiY9lz4uXIcmdVRvfyf/VodAg1uDLA+Uik7Yw+OHZ3inwz2+PGlWkuSK6PNvBBnwa9B8sGm2XHmI6gX+v5TXg2MNW5QA87yAWHa1RF1nQisAY4KLdQdzIXJjyFyOfZY/hrdd880VgfiUpsm8ni1vHZrAZx7EOTX73FuFttUtbXOWoos4Msj+rpfPpVkMaMXSBNfjYiATecU5ql1tnRmg/HzRu3k7MjUJIbL/6vf4wpAgON+tb71JATHaPXWuhRcb7GIqLo9Hcg72J3cGW3xaw2SSOm4RWv/EGXyy1VrilTNPLQgTcg6dO6XG4DrzI2+EG7fLnS5kfbCbZytdg/w=}
